project:
  type: website
  output-dir: docs
  
website:
  title: "Julian Berger"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: cv.pdf
        text: CV

format:
  html:
    theme: simplex
    css: styles.css
    toc: true

editor: visual

