project:
  type: website
  output-dir: docs

website:
  title: "Julian Berger | collective intelligence | wisdom of crowds | machine learning"
  site-url: julian-berger.github.io
  #google-analytics: "G-3N2FL85753"
  search:
    location: sidebar
    type: overlay
  navbar:
    logo: /images/logo-header.png
    title: false
    pinned: false
    collapse-below: md
  sidebar:
    style: docked  
    collapse-level: 1
    background: light
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/julian-berger-aa847b10a/
        text: "LinkedIn profile"
      - icon: github
        href: https://github.com/julian-berger
        text: "GitHub profile"
      - icon: twitter
        href: https://x.com/officialberger
        text: "twitter profile"
    contents:
      - section: "Home"
        href: index.qmd
      - section: "Projects"
        href: projects/index.qmd
        contents:
          - text: "LLM and Collective Intelligence"
            href: projects/LLMxCI.qmd
          - text: "Human-LLM Ensembles"
            href: projects/llm_humans.qmd
          - text: "Hybrid Confirmation Trees"
            href: projects/hct.qmd
          - text: "Independent aggregation is better than AI advice"
            href: projects/hct_vs_ai.qmd
          - text: "Human learning and AI"
            href: projects/ai_learning.qmd
            
          - text: "Efficient Crowds"
            href: projects/crowd_stop.qmd
          - text: "Interpretable Credit Scores"
            href: projects/credit.qmd
          - text: "Debtor Behavior"
            href: projects/debt.qmd
  page-footer:
    left: |
      <br>
      Copyright &copy; 2024 Julian Berger<br>
      This website was created with 
      [![](/images/quarto.png){fig-alt="Quarto" width=65px}](https://quarto.org)<br>
      Design by [Dr. Daniel Kapitan](https://kapitan.net/)<br>
    center: |
      <br>
      __Email:__<br>
      [berger [at] mpib-berlin.mpg.de](mailto::berger [at] mpib-berlin.mpg.de)
    right: |
      <br>

format:
  html:
    page-layout: full
    date-format: "MMM YYYY"
    theme:
      light:
        - flatly
        - mozilla.scss
    css: styles.css
    toc: false

execute: 
  freeze: auto
